# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: 📝 Generate Docs

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with: {enable-cache: true}
      - run: uv sync --no-default-groups --group docs
      - run: uv run mkdocs gh-deploy --force
