# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: 🐍 📦 Publish Python distribution to PyPI

on:
  release:
    types: ["published"]

permissions:
  contents: read
  id-token: write

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://pypi.org/p/dbt-datadict
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - run: uv publish --token ${{ secrets.PYPI_TOKEN }}
